### ISSUE TITLE
IBM Cloud Installation lacks project.json, cannot load Medicine

### ISSUE THREAD

**Issue by brettforbes** [ce-store/ce-store#30]
Hi.
I installed the CE Store by pressing the IBM Cloud button. the app started perfectly, all systems were go. I opened the ui, no problems.

However, it reports a 404 error, exactly the same as on your youtube video. 
![image](https://user-images.githubusercontent.com/24556510/51437874-436a0700-1cf8-11e9-8176-213202155c3b.png)

When I try to install the Medicine application, it says that it cannot find the url
Server error "not found" (404) for url ./json/local_projects.json
![image](https://user-images.githubusercontent.com/24556510/51437867-19b0e000-1cf8-11e9-84f7-924cea38afa7.png)

I'm sure its something small, perhaps I am meant to configure something, please help
brett

**Comment by davebraines** [comment]
Fixed and pushed to master.
The issue with local_projects.json returning a 404 was misleading so I have added an empty local_projects. json file.
The real issue was that the public_projects.json file previously made use of the rawgit service to load CE files directly from github.  This has now been sunset so I have switched the urls over to load the example CE from http://ita-ce.com.  The clickable links in the "Current projects" tabs therefore now work again since they are loading CE from a valid location
